# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install tools
      run: |
        go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
        go get -u github.com/securego/gosec/cmd/gosec
        go get -u github.com/sonatype-nexus-community/nancy

    - name: Run golangci-lint
      run: golangci-lint run

    - name: Run gosec
      run: gosec ./...

    - name: Run nancy
      run: nancy go.sum

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: audit

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
